version: '3'
services:

  producer:
    build: ./producer/
    ports:
      - "8082:8080"
    depends_on:
      - kafka
      - zookeeper

  zookeeper:
    image: "wurstmeister/zookeeper"
    ports:
      - "2181:2181"

  kafka:
    image: "wurstmeister/kafka:2.12-2.5.0"
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_CREATE_TOPICS: "price_changes1:10:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    depends_on:
      - zookeeper
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
